# Generated by Django 5.0.6 on 2024-06-30 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='forkids',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sale',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
