# Generated by Django 5.0.6 on 2024-06-30 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_product_forkids_alter_product_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sale',
            field=models.DecimalField(blank=True, decimal_places=2, default='0,00', max_digits=5, null=True),
        ),
    ]
