# Generated by Django 5.0.6 on 2024-06-30 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_product_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='forkids',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
