# Generated by Django 5.0.6 on 2024-07-01 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_product_forkids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sale',
            field=models.FloatField(blank=True, default='0,00', null=True),
        ),
    ]
