# Generated by Django 5.0.6 on 2024-07-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_product_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sale',
            field=models.FloatField(default=0.0),
        ),
    ]
